version: "3.6"

services:
  meow:
    container_name: meow-service
    build: ./meow-service 
    depends_on:
      - "postgres"
      - "nats"
    ports:
      - 7272:8080
    environment:
      POSTGRES_DB: "meower"
      POSTGRES_USER: "meower"
      POSTGRES_PASSWORD: "123456"
      NATS_ADDRESS: "nats:4222"
  query:
    container_name: query-service
    build: ./query-service 
    depends_on:
      - "postgres"
      - "nats"
    ports:
      - 7474:8080
    environment:
      POSTGRES_DB: "meower"
      POSTGRES_USER: "meower"
      POSTGRES_PASSWORD: "123456"
      NATS_ADDRESS: "nats:4222"
      ELASTICSEARCH_ADDRESS: "elasticsearch:9200"
  
  pusher:
    container_name: pusher-service
    build: ./pusher-service 
    depends_on:
      - "nats"
    ports:
      - 7676:8080
    environment:
      NATS_ADDRESS: "nats:4222"

  postgres:
    container_name: postgres
    build: ./postgres
    restart: "always"
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: "meower"
      POSTGRES_USER: "meower"
      POSTGRES_PASSWORD: "123456"

  nats:
    container_name: nats
    image: "nats-streaming:0.9.2"
    restart: "always"
  
  elasticsearch:
    container_name: elasticsearch
    image: 'docker.elastic.co/elasticsearch/elasticsearch:6.2.3'
  
  nginx:
    container_name: nginx
    build: "./nginx"
    ports:
      - "8080:80"
    depends_on:
      - "meow"
      - "query"
      - "pusher"

networks:
  fullstack:
    driver: bridge